services:
  - type: web
    name: cartella-backend
    env: docker
    plan: free
    region: singapore
    buildCommand: "./mvnw clean package -DskipTests"
    startCommand: "java -jar target/*.jar"
    healthCheckPath: /actuator/health
    envVars:
      - key: SPRING_DATASOURCE_URL
        value: jdbc:mysql://cartella1-miloboycup2121-e1f3.j.aivencloud.com:27345/defaultdb?ssl-mode=REQUIRED
      - key: SPRING_DATASOURCE_USERNAME
        value: avnadmin
      - key: SPRING_DATASOURCE_PASSWORD
        value: AVNS_eUunVOEcsgxifw0pkYI
      - key: SPRING_JPA_HIBERNATE_DDL_AUTO
        value: update